<?php

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_checkoutpayment_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_checkoutpayment'] = array(
    'base' => 'commerce_checkoutpayment',
    'title' => t('Credit / Debit cards (Checkout.com)'),
    'short_title' => t('Credit / Debit cards (Checkout.com)'),
    'description' => t('Payment method for Checkout.com'),
    'terminal' => FALSE,
    'offsite' => commerce_checkoutpayment_check_method_type(),
    'offsite_autoredirect' => FALSE,
    'callbacks' => array(
      'submit_form_submit' => 'commerce_checkoutpayment_submit_charge',
    ),
  );

  return $payment_methods;
}

/*
 * Return TRUE or FALSE indicating whether or not the customer 
 * must be redirected depending on the payment method type.
 */
function commerce_checkoutpayment_check_method_type(){

  $payment_method = commerce_payment_method_instance_load('commerce_checkoutpayment|commerce_payment_commerce_checkoutpayment');
  if($payment_method['settings']['type'] == 'pci'){
    return FALSE;
  }
  else{
    return TRUE;
  }
}

/**
 * Returns the default settings for the Checkout.Com payment method.
 */
function commerce_checkoutpayment_settings_default() {

  return array(
    'mode' => 'live',
    'type' => 'pci',
    'localpayment' => 'false',
    'timeout' => 60,
    'card_types' => array(),
    'payment_action' => COMMERCE_CREDIT_AUTH_ONLY,
    'autocaptime' => 0
  );
}

/**
 * Payment method callback: settings form.
 */
function commerce_checkoutpayment_settings_form($settings = array()) {
  $form = array();

  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.credit_card');

  // Merge default settings into the stored settings array.
  $settings = (array) $settings + commerce_checkoutpayment_settings_default();
  $form['private_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Private Key'),
    '#description' => t('The Checkout.com account secret API key to use .'),
    '#default_value' => $settings['private_key'],
  );

  $form['public_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Publishable API Key'),
    '#description' => t('The Checkout.com account publishable API key to use.'),
    '#default_value' => $settings['public_key'],
  );

  $form['mode'] = array(
    '#type' => 'select',
    '#title' => t('Transaction Server'),
    '#description' => t('Perform transactions on the production server or on the testing server.'),
    '#default_value' => $settings['mode'],
    '#options' => array(
      'live' => t('Live - use for processing real transactions'),
      'sandbox' => t('Test - sandbox for testing. Require a test account'),
    ),
  );

  $form['payment_action'] = array(
    '#type' => 'select',
    '#title' => t('Transaction Method'),
    '#description' => t('The processing method to use for each transaction.'),
    '#default_value' => $settings['payment_action'],
    '#options' => array(
      COMMERCE_CREDIT_AUTH_CAPTURE => t('Authorization and capture'),
      COMMERCE_CREDIT_AUTH_ONLY => t('Authorization only (requires manual or automated capture after checkout)'),
    ),
  );

  $form['autocaptime'] = array(
    '#type' => 'textfield',
    '#title' => t('Set Gateway auto capture time.'),
    '#description' => t('Set how long will the payment be capture.'),
    '#default_value' => $settings['autocaptime'],
  );

  $form['card_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Limit accepted credit cards to the following types (PCI only)'),
    '#description' => t('If you want to limit acceptable card types, you should only select those supported by your merchant account.') . '<br />' . t('If none are checked, any credit card type will be accepted.'),
    '#options' => commerce_payment_credit_card_types(),
    '#default_value' => $settings['card_types'],
  );
  $form['localpayment'] = array(
    '#type' => 'select',
    '#title' => t('Enable LocalPayment'),
    '#options' => array(
      'true' => t('Yes'),
      'false' => t('No'),
    ),
    '#default_value' => $settings['localpayment'],
  );

  $form['type'] = array(
    '#type' => 'select',
    '#title' => t('Method Type (Pci enabled)'),
    '#description' => t('Verify gateway server SSL certificate on connection?'),
    '#options' => array(
      'pci' => t('Yes'),
      'nonpci' => t('No'),
    ),
    '#default_value' => $settings['type'],
  );

  $form['timeout'] = array(
    '#type' => 'textfield',
    '#title' => t('Set Gateway timeout.'),
    '#description' => t('Set how long request timeout on server.'),
    '#default_value' => $settings['timeout'],
  );

  return $form;
}

/**
 * Payment method callback: checkout form.
 */
function commerce_checkoutpayment_submit_form($payment_method, $pane_values, $checkout_pane, $order) {

  $instance = _getInstance($payment_method);
  return $instance->submit_form($payment_method, $pane_values, $checkout_pane, $order);
}

/**
 * Payment method callback: submit form validation.
 */
function commerce_checkoutpayment_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {

  $instance = _getInstance($payment_method); 
  $data = $instance->getExtraInit($order,$payment_method);

  if ($payment_method['settings']['type'] == 'pci') {
    // Validate the credit card fields.
    module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.credit_card');

    $settings = array(
      'form_parents' => array_merge($form_parents, array('credit_card')),
    );

    if (!commerce_payment_credit_card_validate($pane_values['credit_card'], $settings)) {
      return FALSE;
    }
  }
  else {  
    if (empty($pane_values['credit_card']['cko-cc-paymenToken'])) {
      drupal_set_message($data['paymentToken']['message'], 'error');
      return  FALSE;
    }
    return TRUE;
  }
}

/**
 * Retrieves all active instances definitions.
 */
function _getInstance($settings) {

  module_load_include('php', 'commerce_checkoutpayment', 'includes/autoload');

  switch ($settings['settings']['type']) {
    case 'pci':
      $_instance = CheckoutApi_Lib_Factory::getInstance('methods_creditcardpci');
      break;

    default:
      $_instance = CheckoutApi_Lib_Factory::getInstance('methods_creditcard');
      break;
  }

  return $_instance;
}

/**
 * Imitates the checkout form submission callback for the Checkout.com payment method.
 */
function commerce_checkoutpayment_submit_charge($payment_method, $pane_form, $pane_values, $order, $charge) {

  if ($payment_method['settings']['type'] == 'pci') {
    $instance = _getInstance($payment_method);
 
    return $instance->submitFormCharge($payment_method, $pane_form, $pane_values, $order, $charge);
  }
  else {

    return TRUE;
  }
}

/**
 * Implements hook_menu().
 */
function commerce_checkoutpayment_menu() {

  $item = array();

  $items['checkoutapi/process'] = array(
    'title' => 'Ipn checkout',
    'page callback' => 'commerce_checkoutpayment_process_order',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['commerce_checkoutpayment/success'] = array(
    'title' => 'Success page',
    'page callback' => 'commerce_checkoutpayment_success_order',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * Get order status updates
 * Webhook url : example.com/checkoutapi/process
 */
function commerce_checkoutpayment_process_order() {

  $payment_method = commerce_payment_method_instance_load('commerce_checkoutpayment|commerce_payment_commerce_checkoutpayment');
  $post_data = file_get_contents('php://input');
  if ($post_data) {
    $api = CheckoutApi_Api::getApi(array('mode' => $payment_method['settings']['mode']));
    $object_charge = $api->chargeToObj($post_data);

    if ($object_charge->isValid()) {

      /*
       * Need to get track id
       */
      $order_id = $object_charge->getTrackId();

      $order = commerce_order_load($order_id);
      $charge = $order->commerce_order_total[LANGUAGE_NONE][0];

      $transaction = commerce_payment_transaction_new('commerce_checkoutpayment', $order->order_id);
      $transaction->instance_id = $payment_method['instance_id'];
      $transaction->amount = $charge['amount'];
      $transaction->currency_code = $charge['currency_code'];

      if ($object_charge->getCaptured()) {

        $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
        $transaction->message = 'Your transaction has been successfully captured';
        commerce_payment_transaction_save($transaction);
        commerce_order_status_update($order, 'processing', $skip_save = FALSE, TRUE, $log = 'Your payment has been successfully completed');
      }
      elseif ($object_charge->getRefunded()) {

        $transaction->message = 'Your payment has been refunded';
        $transaction->status = COMMERCE_PAYMENT_STATUS_FAILURE;
        commerce_payment_transaction_save($transaction);
        commerce_order_status_update($order, 'canceled', $skip_save = FALSE, TRUE, $log = 'Your payment has been refunded');
      }
      elseif (!$object_charge->getAuthorised()) {

        $transaction->message = 'Your payment has been canceled';
        $transaction->status = COMMERCE_PAYMENT_STATUS_FAILURE;
        commerce_payment_transaction_save($transaction);
        commerce_order_status_update($order, 'canceled', $skip_save = FALSE, TRUE, $log = 'Your payment has been canceled');
      }
    }
    else {
      watchdog('commerce_checkoutpayment', '!charge', array('!charge' => $object_charge->getRawRespond()), WATCHDOG_WARNING);
    }
  }
  return NULL;
}

/*
 * Mobile Redirect to success page
 * Success url : example.com/commerce_checkoutpayment/success
 */
function commerce_checkoutpayment_success_order() {
  global $user;

  if(!isset($_POST['cko-payment-token'])){
    drupal_goto();
  }

  module_load_include('php', 'commerce_checkoutpayment', 'includes/autoload');

  $payment_method = commerce_payment_method_instance_load('commerce_checkoutpayment|commerce_payment_commerce_checkoutpayment');

  $config['authorization'] = $payment_method['settings']['private_key'];
  $config['paymentToken'] = $_POST['cko-payment-token'];

  $api = CheckoutApi_Api::getApi(array('mode' => $payment_method['settings']['mode']));
  $object_charge = $api->verifyChargePaymentToken($config);

  $order_id = isset($_POST['cko-track-id']) && !empty($_POST['cko-track-id'])? $_POST['cko-track-id'] : $object_charge->getTrackId();
  $order = commerce_order_load($order_id);
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $order_total = $order_wrapper->commerce_order_total->value();

  $transaction = commerce_payment_transaction_new($payment_method['method_id'], $order->order_id);
  $transaction->instance_id = $payment_method['instance_id'];
  $transaction->amount = $order_total['amount'];
  $transaction->currency_code = $order_total['currency_code'];
  $transaction->payload[REQUEST_TIME] = $object_charge->getCreated();

  if (preg_match('/^1[0-9]+$/', $object_charge->getResponseCode())) {

    $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
    $transaction->message = 'Your transaction has been successfully authorized with transaction id : ' . $object_charge->getId();

    commerce_payment_transaction_save($transaction);
    $order = commerce_order_status_update($order, 'checkout_complete', $skip_save = FALSE, TRUE, $log = 'Your payment has been successfully completed');

  }
  else {
    watchdog('checkoutpayment_return_url', '!charge', array('!charge' => $object_charge->getRawRespond()), WATCHDOG_WARNING);
  }
  //calling this method order status will be changed to "Checkout_complete", this method will fire commerce_checkout_rule()
  //In commerce_checkout_rule(), we can send email to client to notify checkout is complete.
  commerce_checkout_complete($order);
  //redirect to order completed page or review page
  return drupal_goto(commerce_checkout_order_uri($order));
}

/**
 * Payment method callback: redirect form.
 */
function commerce_checkoutpayment_redirect_form ($form, &$form_state, $order, $payment_method){

  $instance = _getInstance($payment_method); 
  $data = $instance->getExtraInit($order,$payment_method);

  $form['pay_method_container'] = array(
        '#type' => 'hidden',
        '#attributes' => array(
            'class' => array('widget-container')
        ),
    );
  $form['cko-cc-redirectUrl'] = array(
    '#type' => 'hidden',
    '#value' => '',
    '#attributes' => array(
        'id' => array('cko-cc-redirectUrl')
    ),
  );
  $form['cko-cc-paymenToken'] = array(
        '#type' => 'hidden',
        '#value' => '',
        '#attributes' => array(
            'id' => array('cko-cc-paymenToken')
        ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Proceed to Checkout.Com'),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'commerce_checkoutpayment') . '/includes/methods/js/checkoutapi.js' => array(
          'type' => 'file',
        ),
        array(
          'data' => array('commerce_checkoutpayment' => $data['script']),
          'type' => 'setting',
        ),
      ),
    ),
  );

  $form['#action'] = url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key']);

  return $form;
}

/**
 * Payment method callback: redirect form return submission.
 */
function commerce_checkoutpayment_redirect_form_submit($order, $payment_method){

  $instance = _getInstance($payment_method);
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $order_total = $order_wrapper->commerce_order_total->value();
  $charge['amount'] = $order_total['amount'];
  $charge['currency_code'] = $order_total['currency_code'];
  $pane_values['cko-cc-paymenToken'] = $_POST['cko-cc-paymenToken'];
  $pane_values['cko-cc-redirectUrl'] = $_POST['cko-cc-redirectUrl'];

  return $instance->submitFormCharge($payment_method, $pane_form = NULL, $pane_values, $order, $charge);
}